name: Build and Run NGINX Docker Image

on:
  push:
    branches:
      - main  # Trigger this action on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-nginx-image .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 my-nginx-image


