
name: Docker
on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker

    - name: Build Docker image
        run: |
          docker build -t hello-python-docker .
        
      - name: Run Docker container
        run: |
          docker run --name hello-python-container hello-python-docker
        
      - name: Display Docker container logs
        run: |
          docker logs hello-python-container

      - name: Clean up
        run: |
          docker stop hello-python-container
          docker rm hello-python-container